# Generated by Django 4.2.9 on 2024-02-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_product_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["title"], "verbose_name_plural": "Categories"},
        ),
    ]
