# Generated by Django 4.2.9 on 2024-02-13 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product", "0004_userinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "В процессе"),
                            ("completed", "Завершен"),
                            ("canceled", "Отменен"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "address_option",
                    models.CharField(
                        choices=[
                            ("default", "Использовать адрес по умолчанию"),
                            ("new", "Использовать новый адрес"),
                        ],
                        default="default",
                        max_length=150,
                    ),
                ),
                ("new_address", models.CharField(blank=True, max_length=150)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("client_products", models.ManyToManyField(to="product.product")),
            ],
        ),
    ]
